//! - [ ] basename
//! - [ ] blkid
//! - [ ] chroot
//! - [ ] cpio
//! - [ ] df
//! - [ ] dirname
//! - [ ] fdflush
//! - [ ] fdformat
//! - [ ] fdisk
//! - [ ] findfs
//! - [ ] freeramdisk
//! - [ ] fsck
//! - [ ] fsck.minix
//! - [ ] fsync
//! - [ ] hdparm
//! - [ ] mkdosfs
//! - [ ] mkfs.minix
//! - [ ] mkfs.vfat
//! - [ ] mknod
//! - [ ] mkswap
//! - [ ] mktemp
//! - [ ] mount
//! - [ ] mountpoint
//! - [ ] raidautorun
//! - [ ] rmmod
//! - [ ] sync
//! - [ ] umount
//! - [ ] volname
