//! - [ ] arp
//! - [ ] arping
//! - [ ] brctl
//! - [ ] comm
//! - [ ] dhcprelay
//! - [ ] dnsd
//! - [ ] dnsdomainname
//! - [ ] ftpd
//! - [ ] ftpget
//! - [ ] ftpput
//! - [ ] hostname
//! - [ ] httpd
//! - [ ] ifconfig
//! - [ ] ifdown
//! - [ ] ifenslave
//! - [ ] ifplugd
//! - [ ] ifup
//! - [ ] inetd
//! - [ ] ip
//! - [ ] ipaddr
//! - [ ] ipcalc
//! - [ ] iplink
//! - [ ] iproute
//! - [ ] iprule
//! - [ ] iptunnel
//! - [ ] microcom
//! - [ ] mt
//! - [ ] nameif
//! - [ ] nc
//! - [ ] netstat
//! - [ ] nslookup
//! - [ ] ntpc
//! - [ ] ntpsync
//! - [ ] route
//! - [ ] slattach
//! - [ ] udhcpc
